'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ErrorAlert, LoadingAlert, SuccessAlert } from '@components/common/StatusAlert';
import { requestWithAuth } from '@features/auth/services/auth.service';
import { getAdminOfficers, getAdminPrisoners } from '@features/admin-users/services/admin-users.service';
import type { AdminOfficer, AdminPrisoner } from '@features/admin-users/types';
import { isApiServiceError } from '@/types/api';

export default function Page() {
  const [officers,setOfficers]=useState<AdminOfficer[]>([]); const [prisoners,setPrisoners]=useState<AdminPrisoner[]>([]); const [loading,setLoading]=useState(true);
  const [prisonerId,setPrisonerId]=useState(''); const [officerId,setOfficerId]=useState(''); const [accessOfficerId,setAccessOfficerId]=useState('');
  const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  const load=async()=>{setLoading(true);try{const [officerPage,prisonerPage]=await Promise.all([getAdminOfficers({page:1,limit:100}),getAdminPrisoners({page:1,limit:100})]);setOfficers(officerPage.items);setPrisoners(prisonerPage.items);setError(null)}catch{setError('Assignment selectors could not be loaded.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const selectableOfficers=useMemo(()=>officers.filter((item)=>item.user.isActive&&item.publicId),[officers]);
  const selectedPrisoner=prisoners.find((item)=>item.publicId===prisonerId); const selectedOfficer=officers.find((item)=>item.publicId===officerId); const selectedAccessOfficer=officers.find((item)=>item.publicId===accessOfficerId);
  const submit=async(event:FormEvent<HTMLFormElement>,kind:'assign'|'access')=>{event.preventDefault();setError(null);setMessage(null);const form=new FormData(event.currentTarget);try{if(kind==='assign')await requestWithAuth(`/admin/prisoners/${prisonerId}/assignment`,undefined,{method:'PATCH',body:JSON.stringify({officerPublicId:officerId||null,reason:form.get('reason')})});else await requestWithAuth(`/admin/officers/${accessOfficerId}/medical-access`,undefined,{method:'PATCH',body:JSON.stringify({medicalAccessLevel:form.get('medicalAccessLevel'),reason:form.get('reason')})});setMessage(kind==='assign'?'Assignment updated and workloads refreshed.':'Medical access updated.');window.dispatchEvent(new Event('jailmeet:notifications-refresh'));await load()}catch(caught){setError(isApiServiceError(caught)?caught.message:'Operation failed')}};
  if(loading&&!officers.length)return <div className="container-xxl container-p-y"><LoadingAlert>Loading assignment data…</LoadingAlert></div>;
  const identity=(item:AdminOfficer|AdminPrisoner|undefined,fallback:string)=>item?<div className="d-flex align-items-center gap-3 border rounded p-2 mb-3 bg-white"><img alt="" src={item.profilePic||fallback} width={52} height={52} className="rounded object-fit-cover"/><div><strong>{item.name}</strong><span className="d-block text-muted">{item.publicId} · {item.user.isActive?'Active':'Inactive'}{'_count'in item?` · ${item._count.assignedPrisoners} assigned`:item.assignedOfficer?` · ${item.assignedOfficer.name}`:' · Unassigned'}</span></div></div>:null;
  return <div className="container-xxl container-p-y"><h1 className="h3 mb-4">Officer Assignments & Access</h1>{message?<SuccessAlert>{message}</SuccessAlert>:null}{error?<ErrorAlert>{error}</ErrorAlert>:null}<div className="row"><div className="col-lg-6 mb-4"><form className="card card-body h-100" onSubmit={(event)=>void submit(event,'assign')}><h2 className="h5">Prisoner assignment</h2><label className="form-label" htmlFor="assignment-prisoner">Prisoner</label><input id="assignment-prisoner" className="form-control mb-2" list="prisoner-options" pattern="PRN-[0-9]+" required value={prisonerId} onChange={(event)=>setPrisonerId(event.target.value.toUpperCase())}/><datalist id="prisoner-options">{prisoners.filter((item)=>item.publicId).map((item)=><option key={item.publicId!} value={item.publicId!}>{item.name} · {item.user.isActive?'Active':'Inactive'} · {item.assignedOfficer?.name||'Unassigned'}</option>)}</datalist>{identity(selectedPrisoner,'/images/avatars/prisoner-default.PNG')}<label className="form-label" htmlFor="assignment-officer">Active Officer (blank to unassign)</label><input id="assignment-officer" className="form-control mb-2" list="officer-options" pattern="OFR-[0-9]+" value={officerId} onChange={(event)=>setOfficerId(event.target.value.toUpperCase())}/><datalist id="officer-options">{selectableOfficers.map((item)=><option key={item.publicId!} value={item.publicId!}>{item.name} · {item._count.assignedPrisoners} assigned</option>)}</datalist>{identity(selectedOfficer,'/images/avatars/officer-default.PNG')}<label className="form-label">Operational reason</label><textarea name="reason" className="form-control mb-3" minLength={10} maxLength={500} required/><button className="btn btn-primary" disabled={!selectedPrisoner||Boolean(officerId&&!selectedOfficer?.user.isActive)} type="submit">Update assignment</button></form></div><div className="col-lg-6 mb-4"><form className="card card-body h-100" onSubmit={(event)=>void submit(event,'access')}><h2 className="h5">Medical access</h2><label className="form-label" htmlFor="access-officer">Active Officer</label><input id="access-officer" className="form-control mb-2" list="officer-options" pattern="OFR-[0-9]+" required value={accessOfficerId} onChange={(event)=>setAccessOfficerId(event.target.value.toUpperCase())}/>{identity(selectedAccessOfficer,'/images/avatars/officer-default.PNG')}<label className="form-label">Access level</label><select name="medicalAccessLevel" className="form-select mb-3"><option>NONE</option><option>SUMMARY</option><option>MANAGE</option></select><label className="form-label">Operational reason</label><textarea name="reason" className="form-control mb-3" minLength={10} maxLength={500} required/><button className="btn btn-primary" disabled={!selectedAccessOfficer?.user.isActive} type="submit">Update access</button></form></div></div></div>;
}
