import { ActionType, AppointmentStatus, FirStatus, MedicalAccessLevel, MedicalTreatmentStatus, Prisma, VisitPassStatus } from '@prisma/client';
import prisma from '../../config/prisma';
import { createPublicReference } from '../../utils/public-reference';
import { recordAudit } from '../audit';
import { getPermanentAdminRecipient } from '../../utils/permanent-admin';
import { createNotification } from '../notifications';

export class OfficerOperationsError extends Error {
  constructor(public statusCode: number, message: string) { super(message); this.name = 'OfficerOperationsError'; }
}

const officerContext = async (userId: string) => {
  const officer = await prisma.officerProfile.findUnique({ where: { userId }, select: { id: true, publicId: true, name: true, medicalAccessLevel: true } });
  if (!officer) throw new OfficerOperationsError(404, 'Officer profile not found');
  return officer;
};
const page = (q: any, totalItems: number) => ({ page: q.page, limit: q.limit, totalItems, totalPages: Math.max(1, Math.ceil(totalItems / q.limit)) });
const notifyPermanentAdmin = async (type: string, title: string, message: string, link: string, key: string, tx: Prisma.TransactionClient) => { const admin = await getPermanentAdminRecipient(tx); if (admin) await createNotification({ userId: admin.id, type, title, message, link, dedupeKey: key }, tx); };
const assignedPrisoner = async (userId: string, publicId: string) => {
  const prisoner = await prisma.prisonerProfile.findFirst({ where: { publicId, assignedOfficer: { userId } }, select: { id: true, publicId: true, name: true } });
  if (!prisoner) throw new OfficerOperationsError(404, 'Assigned prisoner not found');
  return prisoner;
};

export const getOfficerProfile = async (userId: string) => {
  const profile = await prisma.officerProfile.findUnique({ where: { userId }, select: { publicId: true, name: true, profilePic: true, designation: true, department: true, joiningDate: true, shift: true, officeLocation: true, medicalAccessLevel: true, user: { select: { email: true, role: true, isActive: true } }, _count: { select: { assignedPrisoners: true } } } });
  if (!profile) throw new OfficerOperationsError(404, 'Officer profile not found');
  const recentActions = await prisma.auditLog.count({ where: { userId, createdAt: { gte: new Date(Date.now() - 7 * 86400000) } } });
  return { publicId: profile.publicId ?? 'ID unavailable', name: profile.name, profilePic: profile.profilePic, email: profile.user.email, role: profile.user.role, isActive: profile.user.isActive, designation: profile.designation, department: profile.department, joiningDate: profile.joiningDate?.toISOString() ?? null, shift: profile.shift, officeLocation: profile.officeLocation, medicalAccessLevel: profile.medicalAccessLevel, assignedPrisonerCount: profile._count.assignedPrisoners, recentActionCount: recentActions };
};

export const listAssignedPrisoners = async (userId: string, q: any) => {
  const where: Prisma.PrisonerProfileWhereInput = { assignedOfficer: { userId }, ...(q.active !== 'all' ? { user: { isActive: q.active === 'true' } } : {}), ...(q.search ? { OR: [{ name: { contains: q.search, mode: 'insensitive' } }, { publicId: { contains: q.search, mode: 'insensitive' } }] } : {}) };
  const [items, totalItems] = await prisma.$transaction([
    prisma.prisonerProfile.findMany({ where, orderBy: { name: 'asc' }, skip: (q.page - 1) * q.limit, take: q.limit, select: { publicId: true, name: true, profilePic: true, jailName: true, cellNumber: true, user: { select: { isActive: true } }, assignedOfficer: { select: { publicId: true, name: true } } } }),
    prisma.prisonerProfile.count({ where }),
  ]);
  return { items: items.map((x) => ({ ...x, publicId: x.publicId ?? 'ID unavailable', assignedOfficer: x.assignedOfficer ? { ...x.assignedOfficer, publicId: x.assignedOfficer.publicId ?? 'ID unavailable' } : null })), pagination: page(q, totalItems) };
};

export const getAssignedPrisoner = async (userId: string, publicId: string) => {
  const officer = await officerContext(userId);
  const p = await prisma.prisonerProfile.findFirst({ where: { publicId, assignedOfficerId: officer.id }, select: { publicId: true, name: true, age: true, gender: true, dateOfBirth: true, nationality: true, caseDetails: true, admissionDate: true, sentencePeriod: true, jailType: true, jailName: true, cellNumber: true, profilePic: true, user: { select: { isActive: true } }, assignedOfficer: { select: { publicId: true, name: true } }, appointments: { orderBy: { requestedDate: 'desc' }, take: 10, select: { reference: true, requestedDate: true, status: true, visitPass: { select: { status: true, checkedInAt: true } } } }, paroleRequests: { orderBy: { createdAt: 'desc' }, take: 10, select: { reference: true, status: true, fromDate: true, toDate: true } }, firRecords: { where: { archivedAt: null }, orderBy: { dateFiled: 'desc' }, select: { reference: true, firNumber: true, dateFiled: true, status: true } }, medicalRecords: { where: { archivedAt: null }, orderBy: { checkupDate: 'desc' }, take: 10, select: { reference: true, bloodGroup: true, allergies: true, checkupDate: true, treatmentStatus: true, followUpDate: true, operationalInstructions: true } } } });
  if (!p) throw new OfficerOperationsError(404, 'Assigned prisoner not found');
  const { medicalRecords, ...safePrisoner } = p;
  return { ...safePrisoner, publicId: p.publicId ?? 'ID unavailable', dateOfBirth: p.dateOfBirth?.toISOString() ?? null, admissionDate: p.admissionDate.toISOString(), medicalSummary: officer.medicalAccessLevel === MedicalAccessLevel.NONE ? null : medicalRecords };
};

const firSelect = { reference: true, firNumber: true, description: true, dateFiled: true, status: true, lastChangeReason: true, archivedAt: true, archiveReason: true, createdAt: true, updatedAt: true, prisoner: { select: { publicId: true, name: true } }, createdByOfficer: { select: { publicId: true, name: true } }, updatedByOfficer: { select: { publicId: true, name: true } } } as const;
export const listFirRecords = async (userId: string, q: any) => {
  const where: Prisma.FirRecordWhereInput = { prisoner: { assignedOfficer: { userId }, ...(q.prisonerPublicId ? { publicId: q.prisonerPublicId } : {}) }, ...(q.status ? { status: q.status as FirStatus } : {}), ...(q.search ? { OR: [{ reference: { contains: q.search, mode: 'insensitive' } }, { firNumber: { contains: q.search, mode: 'insensitive' } }, { prisoner: { name: { contains: q.search, mode: 'insensitive' } } }] } : {}) };
  const [items, totalItems] = await prisma.$transaction([prisma.firRecord.findMany({ where, orderBy: { dateFiled: 'desc' }, skip: (q.page - 1) * q.limit, take: q.limit, select: firSelect }), prisma.firRecord.count({ where })]);
  return { items, pagination: page(q, totalItems) };
};
export const getFirRecord = async (userId: string, reference: string) => { const item = await prisma.firRecord.findFirst({ where: { reference, prisoner: { assignedOfficer: { userId } } }, select: firSelect }); if (!item) throw new OfficerOperationsError(404, 'FIR record not found'); return item; };
export const createFirRecord = async (userId: string, publicId: string, body: any) => { const [officer, prisoner] = await Promise.all([officerContext(userId), assignedPrisoner(userId, publicId)]); const reference = createPublicReference('FIR'); return prisma.$transaction(async (tx) => { const item = await tx.firRecord.create({ data: { reference, prisonerId: prisoner.id, firNumber: body.firNumber, description: body.description, dateFiled: new Date(body.dateFiled), status: body.status, createdByOfficerId: officer.id, updatedByOfficerId: officer.id, lastChangeReason: 'Record created' }, select: firSelect }); await recordAudit({ userId, action: ActionType.CREATE, entity: 'FirRecord', entityReference: reference, result: 'SUCCESS', summary: 'FIR record created; fields: firNumber, description, dateFiled, status.' }, tx); await notifyPermanentAdmin('FIR_IMPORTANT_CHANGE','FIR record created',`${reference} for ${publicId} requires oversight.`,`/admin/fir-records?reference=${reference}`,`FIR_IMPORTANT_CHANGE:${reference}:CREATE`,tx); return item; }); };
export const updateFirRecord = async (userId: string, reference: string, body: any) => {
  const officer = await officerContext(userId);
  const existing = await getFirRecord(userId, reference);
  if (existing.status === FirStatus.ARCHIVED) throw new OfficerOperationsError(409, 'Archived FIR records cannot be changed');
  const transitions: Record<FirStatus, FirStatus[]> = {
    OPEN: [FirStatus.OPEN, FirStatus.UNDER_REVIEW, FirStatus.CLOSED],
    UNDER_REVIEW: [FirStatus.OPEN, FirStatus.UNDER_REVIEW, FirStatus.CLOSED],
    CLOSED: [FirStatus.UNDER_REVIEW, FirStatus.CLOSED],
    ARCHIVED: [FirStatus.ARCHIVED],
  };
  if (body.status && !transitions[existing.status].includes(body.status)) throw new OfficerOperationsError(409, `FIR status cannot change from ${existing.status} to ${body.status}`);
  const { changeReason, ...changes } = body;
  const fields = Object.keys(changes);
  return prisma.$transaction(async (tx) => {
    const item = await tx.firRecord.update({ where: { reference }, data: { ...changes, dateFiled: body.dateFiled ? new Date(body.dateFiled) : undefined, updatedByOfficerId: officer.id, lastChangeReason: changeReason }, select: firSelect });
    await recordAudit({ userId, action: ActionType.UPDATE, entity: 'FirRecord', entityReference: reference, result: 'SUCCESS', summary: `FIR fields changed: ${fields.join(', ')}.` }, tx);
    await notifyPermanentAdmin('FIR_IMPORTANT_CHANGE', 'FIR record updated', `${reference} was updated and is available for oversight.`, `/admin/fir-records?reference=${reference}`, `FIR_IMPORTANT_CHANGE:${reference}:${item.updatedAt.toISOString()}`, tx);
    return item;
  });
};
export const archiveFirRecord = async (userId: string, reference: string, reason: string) => { const officer = await officerContext(userId); await getFirRecord(userId, reference); return prisma.$transaction(async (tx) => { const item = await tx.firRecord.update({ where: { reference }, data: { status: FirStatus.ARCHIVED, archivedAt: new Date(), archiveReason: reason, lastChangeReason: reason, updatedByOfficerId: officer.id }, select: firSelect }); await recordAudit({ userId, action: ActionType.ARCHIVE, entity: 'FirRecord', entityReference: reference, result: 'SUCCESS', summary: 'FIR record archived.' }, tx); await notifyPermanentAdmin('FIR_IMPORTANT_CHANGE','FIR record archived',`${reference} was archived with a recorded reason.`,`/admin/fir-records?reference=${reference}`,`FIR_IMPORTANT_CHANGE:${reference}:ARCHIVE`,tx); return item; }); };
export const getFirHistory = async (userId: string, reference: string) => { await getFirRecord(userId, reference); return prisma.auditLog.findMany({ where: { entity: 'FirRecord', entityReference: reference }, orderBy: { createdAt: 'desc' }, select: { action: true, result: true, details: true, createdAt: true, user: { select: { officerProfile: { select: { publicId: true, name: true } } } } } }); };

const medicalSummarySelect = { reference: true, bloodGroup: true, allergies: true, checkupDate: true, treatmentStatus: true, followUpDate: true, operationalInstructions: true, archivedAt: true, prisoner: { select: { publicId: true, name: true } } } as const;
const medicalManageSelect = { ...medicalSummarySelect, checkupDetails: true, medicalProfessional: true, diagnosis: true, medication: true, restrictedNotes: true, archiveReason: true, createdAt: true, updatedAt: true, createdByOfficer: { select: { publicId: true, name: true } }, updatedByOfficer: { select: { publicId: true, name: true } } } as const;
const requireMedical = async (userId: string, manage = false) => { const officer = await officerContext(userId); if (officer.medicalAccessLevel === MedicalAccessLevel.NONE || (manage && officer.medicalAccessLevel !== MedicalAccessLevel.MANAGE)) { await prisma.$transaction(async (tx) => { await recordAudit({ userId, action: ActionType.VIEW, entity: 'MedicalRecord', entityReference: 'ACCESS-CONTROL', result: 'BLOCKED', summary: 'Unauthorized medical access was blocked.' }, tx); await notifyPermanentAdmin('MEDICAL_ACCESS_BLOCKED','Unauthorized medical access blocked',`Officer ${officer.publicId ?? 'ID unavailable'} was blocked by medical-access policy.`, '/admin/system-integrity', `MEDICAL_ACCESS_BLOCKED:${officer.publicId}:${new Date().toISOString().slice(0,13)}`, tx); }); throw new OfficerOperationsError(403, manage ? 'MANAGE medical access is required' : 'Medical access is not authorized'); } return officer; };
export const listHealthRecords = async (userId: string, q: any) => { const officer = await requireMedical(userId); const where: Prisma.MedicalRecordWhereInput = { prisoner: { assignedOfficerId: officer.id, ...(q.prisonerPublicId ? { publicId: q.prisonerPublicId } : {}) }, ...(q.status ? { treatmentStatus: q.status as MedicalTreatmentStatus } : {}), ...(q.search ? { OR: [{ reference: { contains: q.search, mode: 'insensitive' } }, { prisoner: { name: { contains: q.search, mode: 'insensitive' } } }] } : {}) }; const [items, totalItems] = await prisma.$transaction([prisma.medicalRecord.findMany({ where, orderBy: { checkupDate: 'desc' }, skip: (q.page - 1) * q.limit, take: q.limit, select: officer.medicalAccessLevel === MedicalAccessLevel.MANAGE ? medicalManageSelect : medicalSummarySelect }), prisma.medicalRecord.count({ where })]); return { accessLevel: officer.medicalAccessLevel, items, pagination: page(q, totalItems) }; };
export const getHealthSummary = async (userId: string, publicId: string) => { const officer = await requireMedical(userId); await assignedPrisoner(userId, publicId); return { accessLevel: officer.medicalAccessLevel, items: await prisma.medicalRecord.findMany({ where: { prisoner: { publicId, assignedOfficerId: officer.id }, archivedAt: null }, orderBy: { checkupDate: 'desc' }, select: medicalSummarySelect }) }; };
export const getHealthRecord = async (userId: string, reference: string) => { const officer = await requireMedical(userId); const item = await prisma.medicalRecord.findFirst({ where: { reference, prisoner: { assignedOfficerId: officer.id } }, select: officer.medicalAccessLevel === MedicalAccessLevel.MANAGE ? medicalManageSelect : medicalSummarySelect }); if (!item) throw new OfficerOperationsError(404, 'Health record not found'); if (officer.medicalAccessLevel === MedicalAccessLevel.MANAGE) await recordAudit({ userId, action: ActionType.VIEW, entity: 'MedicalRecord', entityReference: reference, result: 'RESTRICTED_VIEW', summary: 'Authorized restricted health-record details viewed.' }); return { accessLevel: officer.medicalAccessLevel, record: item }; };
export const createHealthRecord = async (userId: string, publicId: string, body: any) => { const [officer, prisoner] = await Promise.all([requireMedical(userId, true), assignedPrisoner(userId, publicId)]); const reference = createPublicReference('MED'); return prisma.$transaction(async (tx) => { const item = await tx.medicalRecord.create({ data: { ...body, reference, prisonerId: prisoner.id, checkupDate: body.checkupDate ? new Date(body.checkupDate) : undefined, followUpDate: body.followUpDate ? new Date(body.followUpDate) : undefined, createdByOfficerId: officer.id, updatedByOfficerId: officer.id }, select: medicalManageSelect }); await recordAudit({ userId, action: ActionType.CREATE, entity: 'MedicalRecord', entityReference: reference, result: 'SUCCESS', summary: 'Authorized health record created.' }, tx); if (body.treatmentStatus === MedicalTreatmentStatus.FOLLOW_UP_REQUIRED || (body.followUpDate && new Date(body.followUpDate) <= new Date())) await notifyPermanentAdmin('MEDICAL_ATTENTION','Medical follow-up requires attention',`${reference} for ${publicId} requires operational follow-up.`,`/admin/health-records?reference=${reference}`,`MEDICAL_ATTENTION:${reference}`,tx); return item; }); };
export const updateHealthRecord = async (userId: string, reference: string, body: any) => { const officer = await requireMedical(userId, true); await getHealthRecord(userId, reference); return prisma.$transaction(async (tx) => { const { changeReason: _reason, ...changes } = body; const item = await tx.medicalRecord.update({ where: { reference }, data: { ...changes, checkupDate: body.checkupDate ? new Date(body.checkupDate) : undefined, followUpDate: body.followUpDate ? new Date(body.followUpDate) : undefined, updatedByOfficerId: officer.id }, select: medicalManageSelect }); await recordAudit({ userId, action: ActionType.UPDATE, entity: 'MedicalRecord', entityReference: reference, result: 'SUCCESS', summary: `Health-record fields changed: ${Object.keys(changes).join(', ')}.` }, tx); return item; }); };
export const archiveHealthRecord = async (userId: string, reference: string, reason: string) => { const officer = await requireMedical(userId, true); await getHealthRecord(userId, reference); return prisma.$transaction(async (tx) => { const item = await tx.medicalRecord.update({ where: { reference }, data: { treatmentStatus: MedicalTreatmentStatus.ARCHIVED, archivedAt: new Date(), archiveReason: reason, updatedByOfficerId: officer.id }, select: medicalManageSelect }); await recordAudit({ userId, action: ActionType.ARCHIVE, entity: 'MedicalRecord', entityReference: reference, result: 'SUCCESS', summary: 'Health record archived.' }, tx); return item; }); };

export const officerSearch = async (userId: string, q: string, limit: number) => { const officer = await officerContext(userId); const common = { contains: q, mode: 'insensitive' as const }; const [prisoners, appointments, paroles, passes, fir, medical] = await prisma.$transaction([prisma.prisonerProfile.findMany({ where: { assignedOfficerId: officer.id, OR: [{ publicId: common }, { name: common }] }, take: limit, select: { publicId: true, name: true } }), prisma.appointment.findMany({ where: { prisoner: { assignedOfficerId: officer.id }, OR: [{ reference: common }, { visitor: { publicId: common } }] }, take: limit, select: { reference: true, visitor: { select: { publicId: true, name: true } }, prisoner: { select: { publicId: true, name: true } } } }), prisma.paroleRequest.findMany({ where: { prisoner: { assignedOfficerId: officer.id }, reference: common }, take: limit, select: { reference: true, prisoner: { select: { publicId: true, name: true } } } }), prisma.visitPass.findMany({ where: { passCode: q, appointment: { prisoner: { assignedOfficerId: officer.id } } }, take: 1, select: { passCode: true, appointment: { select: { reference: true } } } }), prisma.firRecord.findMany({ where: { prisoner: { assignedOfficerId: officer.id }, OR: [{ reference: common }, { firNumber: common }] }, take: limit, select: { reference: true, firNumber: true, prisoner: { select: { publicId: true, name: true } } } }), prisma.medicalRecord.findMany({ where: officer.medicalAccessLevel === MedicalAccessLevel.NONE ? { id: '__not_authorized__' } : { prisoner: { assignedOfficerId: officer.id }, reference: common }, take: limit, select: { reference: true, prisoner: { select: { publicId: true, name: true } } } })]); return { prisoners, appointments, paroles, visitPasses: passes, firRecords: fir, healthRecords: medical }; };
export const officerSafeSearch = async (userId: string, q: string, limit: number) => {
  const officer = await officerContext(userId);
  const common = { contains: q, mode: 'insensitive' as const };
  const [operational, visitors, prisoners] = await Promise.all([
    officerSearch(userId, q, limit),
    prisma.visitorProfile.findMany({
      where: {
        appointments: { some: { prisoner: { assignedOfficerId: officer.id } } },
        OR: [{ publicId: common }, { name: common }, { user: { email: common } }],
      },
      take: limit,
      select: { publicId: true, name: true, profilePic: true, user: { select: { role: true, isActive: true } } },
    }),
    prisma.prisonerProfile.findMany({
      where: { assignedOfficerId: officer.id, OR: [{ publicId: common }, { name: common }] },
      take: limit,
      select: { publicId: true, name: true, profilePic: true, user: { select: { role: true, isActive: true } } },
    }),
  ]);
  return { ...operational, visitors, prisoners };
};
export const officerActivity = async (userId: string, q: any) => { const where: Prisma.AuditLogWhereInput = { userId, ...(q.action ? { action: q.action as ActionType } : {}), ...(q.dateFrom || q.dateTo ? { createdAt: { ...(q.dateFrom ? { gte: new Date(q.dateFrom) } : {}), ...(q.dateTo ? { lte: new Date(q.dateTo) } : {}) } } : {}) }; const [items, totalItems] = await prisma.$transaction([prisma.auditLog.findMany({ where, orderBy: { createdAt: 'desc' }, skip: (q.page - 1) * q.limit, take: q.limit, select: { action: true, entity: true, entityReference: true, result: true, details: true, createdAt: true } }), prisma.auditLog.count({ where })]); return { items, pagination: page(q, totalItems) }; };
export const listEscalatedSupport = async (userId: string) => { const officer = await officerContext(userId); return prisma.prisonerSupportRequest.findMany({ where: { escalatedToOfficerId: officer.id, prisoner: { assignedOfficerId: officer.id } }, orderBy: { escalatedAt: 'desc' }, select: { reference: true, category: true, subject: true, message: true, status: true, escalatedAt: true, officerResponse: true, officerHandledAt: true, prisoner: { select: { publicId: true, name: true } } } }); };
export const respondEscalatedSupport = async (userId: string, requestId: string, body: any) => { const officer = await officerContext(userId); const request = await prisma.prisonerSupportRequest.findFirst({ where: { reference: requestId, escalatedToOfficerId: officer.id, prisoner: { assignedOfficerId: officer.id } }, select: { reference: true } }); if (!request) throw new OfficerOperationsError(404, 'Escalated support request not found'); return prisma.$transaction(async (tx) => { const item = await tx.prisonerSupportRequest.update({ where: { reference: requestId }, data: { officerResponse: body.response, officerHandledAt: body.handled ? new Date() : null }, select: { reference: true, category: true, subject: true, status: true, officerResponse: true, officerHandledAt: true, prisoner: { select: { publicId: true, name: true } } } }); await recordAudit({ userId, action: ActionType.ESCALATE, entity: 'PrisonerSupportRequest', entityReference: item.reference, result: body.handled ? 'HANDLED' : 'COMPLETED', summary: 'Officer responded to an escalated support action.' }, tx); const admin = await getPermanentAdminRecipient(tx); if (admin) await createNotification({ userId: admin.id, type: 'SUPPORT_ESCALATION_COMPLETED', title: 'Officer completed support escalation', message: `${item.reference} received an Officer response and is ready for Admin review.`, link: `/admin/prisoner-support-requests?reference=${item.reference}`, dedupeKey: `SUPPORT_ESCALATION_COMPLETED:${item.reference}:${item.officerHandledAt?.toISOString() ?? 'RESPONSE'}` }, tx); return item; }); };
export const officerReports = async (userId: string, q: any) => { const officer = await officerContext(userId); const date = q.dateFrom || q.dateTo ? { ...(q.dateFrom ? { gte: new Date(q.dateFrom) } : {}), ...(q.dateTo ? { lte: new Date(q.dateTo) } : {}) } : undefined; const scope = { prisoner: { assignedOfficerId: officer.id } }; const week = new Date(Date.now() - 7 * 86400000); const [assignedPrisoners, appointments, completedThisWeek, pendingChanges, pendingParoles, expiredUnusedPasses, firByStatus, medicalAttention, actionCount] = await prisma.$transaction([prisma.prisonerProfile.count({ where: { assignedOfficerId: officer.id } }), prisma.appointment.groupBy({ by: ['status'], where: { ...scope, ...(date ? { requestedDate: date } : {}) }, _count: true }), prisma.appointment.count({ where: { ...scope, status: AppointmentStatus.COMPLETED, updatedAt: { gte: week } } }), prisma.appointmentChangeRequest.count({ where: { appointment: scope, status: 'PENDING' } }), prisma.paroleRequest.count({ where: { ...scope, status: 'PENDING' } }), prisma.visitPass.count({ where: { appointment: scope, OR: [{ status: VisitPassStatus.EXPIRED }, { status: VisitPassStatus.ACTIVE, expiresAt: { lt: new Date() } }] } }), prisma.firRecord.groupBy({ by: ['status'], where: scope, _count: true }), prisma.medicalRecord.count({ where: { ...scope, archivedAt: null, OR: [{ treatmentStatus: MedicalTreatmentStatus.FOLLOW_UP_REQUIRED }, { followUpDate: { lte: new Date() } }] } }), prisma.auditLog.count({ where: { userId, ...(date ? { createdAt: date } : {}) } })]); return { assignedPrisoners, appointmentsByStatus: appointments, visitsCompletedThisWeek: completedThisWeek, pendingChangeRequests: pendingChanges, pendingParoleRequests: pendingParoles, expiredOrUnusedPasses: expiredUnusedPasses, firByStatus, medicalRequestsRequiringAction: medicalAttention, officerActionCount: actionCount }; };
